The objective of this project is to analyze the Electric Vehicle (EV) population data to understand trends in electric vehicle adoption across different regions, vehicle types, and manufacturers. The analysis aims to identify growth patterns in EV usage, the most popular EV brands and models, geographic distribution of electric vehicles, and factors influencing EV adoption such as electric range and CAFV eligibility. The insights generated from this analysis can help policymakers, automotive companies, and energy providers understand EV market trends and make data-driven decisions to support sustainable transportation.

In [1]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"C:\Users\Admin\Downloads\Electric_Vehicle_Population_Data.csv")

In [5]:
df.head(5)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,JN1AZ0CP5C,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,7.0,153331706,POINT (-117.90454 48.54657),AVISTA CORP,5.306595e+10
1,JTMABABA7P,Yakima,Yakima,WA,98903.0,2023,SUBARU,SOLTERRA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,15.0,253586308,POINT (-120.71847 46.55029),PACIFICORP,5.307700e+10
2,1N4AZ1CP1J,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,151.0,37.0,333135022,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5UX43EU09S,Kitsap,Poulsbo,WA,98370.0,2025,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,40.0,23.0,267525737,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303594e+10
4,3C3CFFGE5F,Thurston,Yelm,WA,98597.0,2015,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,87.0,2.0,474468501,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279780 entries, 0 to 279779
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         279780 non-null  object
 1   County                                             279756 non-null  object
 2   City                                               279756 non-null  object
 3   State                                              279780 non-null  object
 4   Postal Code                                        279756 non-null  float64
 5   Model Year                                         279780 non-null  int64
 6   Make                                               279780 non-null  object
 7   Model                                              279780 non-null  object
 8   Electric Vehicle Type                              279780 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  279780 non-null  object
 10  Electric Range                                     279769 non-null  float64
 11  Legislative District                               279080 non-null  float64
 12  DOL Vehicle ID                                     279780 non-null  int64
 13  Vehicle Location                                   279671 non-null  object
 14  Electric Utility                                   279756 non-null  object
 15  2020 Census Tract                                  279756 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 34.2+ MB

In [8]:
df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 Census Tract
count,279756.000000,279780.000000,279769.000000,279080.000000,2.797800e+05,2.797560e+05
mean,98176.111447,2022.074072,39.172256,28.827841,2.462994e+08,5.297189e+10
std,2577.398040,3.059852,78.230356,14.908133,6.346205e+07,1.636194e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.385000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.213867e+08,5.303301e+10
50%,98133.000000,2023.000000,0.000000,32.000000,2.629453e+08,5.303303e+10
75%,98382.000000,2024.000000,32.000000,42.000000,2.790832e+08,5.305394e+10
max,99517.000000,2027.000000,337.000000,49.000000,4.791150e+08,6.601095e+10